{%- from "jenkins-docker/map.jinja" import jenkins with context -%}

version: "3.9"
services:
  dind:
    image: docker:dind
    privileged: True
    volumes:
      - "jenkins-docker-certs:/certs/client"
      - "${JENKINS_DATA:-jenkins-data}:/var/jenkins_home"
    networks:
      jenkins:
        aliases:
          - docker
    environment:
      - "DOCKER_TLS_CERTDIR=/certs"
    ports:
      - "2376:2376"

  blueocean:
    build: .
    restart: on-failure
    networks:
      jenkins:
    environment:
      - "DOCKER_HOST=tcp://docker:2376"
      - "DOCKER_CERT_PATH=/certs/client"
      - "DOCKER_TLS_VERIFY=1"
      {% for name, value in jenkins.environment_variables.items() -%}
      - "{{ name }}={{ value }}"
      {% endfor -%}

    ports:
      - "${PORT:-8080}:8080"
    volumes:
      - "jenkins-docker-certs:/certs/client:ro"
      - "${JENKINS_DATA:-jenkins-data}:/var/jenkins_home"

networks:
  jenkins:

volumes:
  jenkins-docker-certs:
